###получить все ингредиенты
GET http://localhost:8080/ingredient
Content-Type: application/json

###добавление ингредиента1
POST http://localhost:8080/ingredient
Content-Type: application/json

{
  "name": "Творог",
"count": 250,
"measurement": "гр."
}

###добавление ингредиента2
POST http://localhost:8080/ingredient
Content-Type: application/json

{
  "name": "Помидоры",
  "count": 3,
  "measurement": "шт."
}

###добавление ингредиента3
POST http://localhost:8080/ingredient
Content-Type: application/json

{

  "name": "Огурцы",
  "count": 2,
  "measurement": "шт."
}

###редактировать ингредиент
PUT http://localhost:8080/ingredient/1
Content-Type: application/json

###удалить ингредиент
DELETE http://localhost:8080/ingredient/1
Content-Type: application/json