###получить все рецепты
GET http://localhost:8080/recipe

###создание рецепта1
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "id": 1,
  "name": "Сырники из творога",
  "cookingTime": 30,
  "ingredients": [
    {
      "id": 1,
      "name": "Творог",
      "count": 350,
      "measurement": "гр."
    },
    {
      "id": 2,
      "name": "Куриное яйцо",
      "count": 2,
      "measurement": "шт."
    },
    {
      "id": 3,
      "name": "Пшеничная мука",
      "count": 6,
      "measurement": "ст.ложек"
    },
    {
      "id": 4,
      "name": "Сахар",
      "count": 2,
      "measurement": "ст.ложки"
    }
  ],
  "steps":
  {"1": "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте.",
    "2": "Всыпьте в творог муку и тщательно перемешайте.",
"3": "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.",
"4": "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку.",
"5": "По очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду.",
"6": "Обжаривайте сырники 1–2 минуты до появления золотистой корочки.",
"7": "Переверните их на другую сторону и также обжарьте до золотистого состояния.",
"8": "Повторяйте, пока творог не закончится."
}
}


###создание рецепта2
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "id": 2,
  "name": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом",
  "cookingTime": 30
}

