###получить все рецепты
GET http://localhost:8080/recipe
Content-Type: application/json

###создание рецепта1
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Сырники из творога",
  "cookingTime": 30,
  "ingredients": [
    {
      "name": "Творог",
      "count": 350,
      "measurement": "гр."
    },
    {
      "name": "Куриное яйцо",
      "count": 2,
      "measurement": "шт."
    },
    {
      "name": "Пшеничная мука",
      "count": 6,
      "measurement": "ст.ложек"
    },
    {
      "name": "Сахар",
      "count": 2,
      "measurement": "ст.ложки"
    }
  ],
  "steps":
  [
    "Смешайте весь творог с яйцами, сахаром и тщательно всё перемешайте.",
    "Всыпьте в творог муку и тщательно перемешайте.",
    "Поставьте сковороду на средний огонь и налейте в нее подсолнечное масло.",
    "Слепите несколько небольших шариков из получившейся творожной массы и положите их на тарелку.",
    "По очереди обкатывайте творожные шарики в муке и выкладывайте на сковороду.",
    "Обжаривайте сырники 1–2 минуты до появления золотистой корочки.",
    "Переверните их на другую сторону и также обжарьте до золотистого состояния.",
    "Повторяйте, пока творог не закончится."
  ]
}


###создание рецепта2
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "name": "Салат из красной фасоли с творожным сыром, красным луком и сезонным салатом",
  "cookingTime": 30,
  "ingredients": [
    {
      "name": "Специи",
      "count": 0,
      "measurement": "по вкусу"
    },
    {
      "name": "Консервированная фасоль",
      "count": 400,
      "measurement": "гр."
    },
    {
      "name": "Лимон",
      "count": 1,
      "measurement": "шт."
    },
    {
      "name": "Чеснок",
      "count": 2,
      "measurement": "зубчика"
    },
    {
      "name": "Оливковое масло",
      "count": 50,
      "measurement": "мл"
    },
    {
      "name": "Рукола",
      "count": 100,
      "measurement": "гр."
    },
    {
      "name": "Творожный сыр",
      "count": 200,
      "measurement": "гр."
    },
    {
      "name": "Красный лук",
      "count": 50,
      "measurement": "гр."
    }
  ],
  "steps": [
    "Открыть две банки красной фасоли в собственном соку, слить сок и промыть фасоль холодной водой.",
    "Готовую фасоль смешать с мелко нарубленным красным луком, зеленью, давленым чесноком, оливковым маслом, лимонным соком и творожным сыром.",
    "Посолить, поперчить, дать продуктам две минуты притереться друг к другу и подавать к столу."
  ]
}

###удаление рецепта
DELETE http://localhost:8080/recipe/0
Content-Type: application/json

